### ISSUE TITLE
Internal error - unsuported array::outbound_clicks

### ISSUE THREAD

**Issue by kacurez** [keboola/ex-facebook-graph-api#72] opened 2019-05-13 11:22 UTC
https://keboola.slack.com/archives/C09U3R1J4/p1557746189118400
unsuported array::outbound_clicks[{:action_type \"outbound_click\", :value \"1\"}]

**Comment by odinuv** [comment] 2019-05-16 05:28
duplicate of https://github.com/keboola/ex-facebook-graph-api/issues/68

**Closed by odinuv** 2019-05-16 05:28 UTC
